# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d997ccd001e07d17138912f42d4c1b8242e8a4281157451fda02aeb46b13d6443131a1b6fb17dc806e0533153826d6048e5ffcf0662e8804aaed137686c5366f

test:
  secret_key_base: 0557f9045dcee97fbcbc251b6dd26524248ee30395625db3962bdfdb975e7849bcdae7eb9a0846e6f116124ee430313573a6a520c84b875fb399d3e6a4b3e387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
